### PR TITLE
added new dropdown for rendering large list

### LINKED ISSUE #167: Slowness during the display
As it was reported [on our Slack community](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1635176781017400), some slowness is noticeable using the mini-dashboard.

This slowness is not present when only using instant-meilisearch (the dependency used by this repo).
As you can see:

Mini-dashboard:
https://user-images.githubusercontent.com/20380692/139108096-d4e8d7fc-03f8-4157-adc6-11697c02f239.mp4

Only instant-meilisearch
https://user-images.githubusercontent.com/20380692/139108334-2cd7f9fd-a200-46a2-a618-ced5a453a086.mp4

Also here are the processing time of Instant MeiliSearch

Screenshot 2021-10-26 at 20 43 20

Can interest @bidoubiwa 
Ask for @bidoubiwa for the dataset

### PR DESCRIPTION
**Pull request by vaibhav135**
# Pull Request

## Related issue
Fixes #167 

## What does this PR do?
- This PR fixes the issue where if you load a lot of datasets ( > 1000 ) the dropdown starts to lag and UX becomes super laggy.

Here's the before and after -

**before**
https://github.com/meilisearch/mini-dashboard/assets/39329182/e72f45d7-f143-460e-afe3-e3858e03fc9d

**after**
https://github.com/meilisearch/mini-dashboard/assets/39329182/bc7f94fb-764c-4a9f-b306-6a6890e2e1a2

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Amazong @vaibhav135 I'll be reviewing this asap :) Any idea why the cypress test is failing?

**Comment by vaibhav135** [comment]
> Amazong @vaibhav135 I'll be reviewing this asap :) Any idea why the cypress test is failing?

@bidoubiwa I will check it.

**Comment by vaibhav135** [comment]
@bidoubiwa I have fixed all the tests. Also I saw that in a lot of places we were picking the element for e.g.`ul` directly. Please don't do that moving forward, because that is considered as a bad practise, check [here for more details](https://docs.cypress.io/guides/references/best-practices). Please try to use `data-cy`, `data-testid` or `data-id` for getting an element.

**Review by bidoubiwa — APPROVED** [review]
LGTM !! ✨

Thanks for this information! :) We'll take that into account in the future.

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
