### PR TITLE
Add a Fancy Cloud Button

### PR DESCRIPTION
**Pull request by Kerollmops**
This pull request adds a new fancy button that directly links to the pricing page of Meilisearch. I added some sparkling to make it a little more fun and visible. I will ask for advice on the button text. Currently, it says _Try the Cloud_. I thought about _Easier on the Cloud_, but it's too long.

I followed [this tutorial from _JoshwComeau_ for the sparkles](https://www.joshwcomeau.com/react/animated-sparkles-in-react/) and did the rest myself.

https://github.com/meilisearch/mini-dashboard/assets/3610253/4918136a-545a-4027-bd3d-0a416c952407

### CODE REVIEW

**Comment by Strift** [comment]
Wouldn't it look better on the far right side of the navbar? Between the "API key" button and the help button.

**Comment by davelarkan** [comment]
> We need to chose between this and https://github.com/meilisearch/mini-dashboard/pull/442

I feel like this is a fine start. However, #442 gives us the benefit of adding additional copy to explain why the Cloud might be worth considering.

If we decide to proceed with this issue instead of #442 we still need the ability to hide this button for Cloud users (either via a url query param or some other method)

**Comment by bidoubiwa** [comment]
If we go for this solution, I don't mind adding the query parameter

**Comment by bidoubiwa** [comment]
⚠️ When we decided on the solution, we need to inform the cloud so that they can implement the query parameter.

**Review by bidoubiwa — CHANGES_REQUESTED** [review]

**Comment by brunoocasali** [comment]
Why not have both @bidoubiwa?

**Comment by bidoubiwa** [comment]
It might be a visual spam? I don't know 😅

**Comment by Kerollmops** [comment]
Indeed, but we could add my sparkles ✨ on your top bar @bidoubiwa?

**Comment by brunoocasali** [comment]
> It might be a visual spam? I don't know 😅

I don't see it like that because the banner is dismissable, so the user can opt to remove it, and the button does not imply a visual burden nor induce the user to any mistake.

**Comment by bidoubiwa** [comment]
After discussing with @gmourier. We decided not to add this button currently. Thanks a lot for this contribution 🙏 Sorry it was not merged at the end

**Pull request closed without merging**
