### PR TITLE
Speed up the isObject function

### PR DESCRIPTION
**Pull request by Kerollmops**
The `isObject` function is slowing down the page rendering, so I decided to simplify it by removing the parsing step and replaced it with a simple check of the first and last character, not correct but much faster. MeiliSearch will probably never return invalid JSON objects anyway 😄

There also is the `emotion/css` module that slows down the page rendering.

I also learned that a `yarn build` is much faster as it generates an optimized build 🎉
```bash
yarn build
cd build
python3 -m http.server 8000
```

It could be great if you could make the `yarn build` command to be able to run with the server running on `127.0.0.1:7700` and add these three commands in the readme, it would help others run the server in production and avoid performances issues. 😄

### CODE REVIEW

**Comment by mdubus** [comment]
Thanks a lot for your PR 🙏. 

If we're going for the first-letter and last-letter check, you can optimize even more the isObject function by using the `match` function : 
```
  return value.trim().match(/^{(.*?)}$/)
```

Could you update your PR with this ?

I'm going to have a check at the `emotion/css` to see what I can do. 

For the build server address, would an environment variable like `REACT_APP_MEILI_SERVER_ADDRESS` be ok for you (the environment variable has to start with`REACT_APP`) ?

**Comment by Kerollmops** [comment]
Ok, done! I am not sure a regex is faster than two `charAt` calls but anyway, even with a regex it doesn't appear in the most CPU-intensive function when benchmarking the page rendering.

> I'm going to have a check at the emotion/css to see what I can do.

Thank you 🎉 

> For the build server address, would an environment variable like REACT_APP_MEILI_SERVER_ADDRESS be ok for you (the environment variable has to start withREACT_APP) ?

Yup, it would be great, don't forget to add this in the README, please 😄

**Comment by mdubus** [comment]
@dependabot rebase

**Comment by mdubus** [comment]
bors merge

**Pull request merged**
