### PR TITLE
Replace slack with discord

### LINKED ISSUE #361: Replace Slack with Discord
Since we have moved from Slack Community to Discord, we need to update the Help Center inside the mini-dashboard

### PR DESCRIPTION
**Pull request by mdubus**
# Pull Request

## Related issue
Closes #361

## What does this PR do?
- Replace Slack with Discord
- Remove the now-useless Slack logos

## Screenshots
Capture d’écran 2022-11-30 à 10 59 17

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Review by bidoubiwa — APPROVED** [review]
I think keeping `Logo` in `DiscordLogo` is best. `Discord` could refer to some component detailing lots of stuff about our discord or even widgets that somehow interacts with our discord. 

Nonetheless, its a detail :) feel free to ignore

**Review by bidoubiwa — APPROVED** [review]
🔥

**Comment by Adel-Moumen** [comment]
Hello @mdubus, 

I think the current discord invitation link is outdated. Indeed, when trying to join the discord, I get the error: "Invite invalid". 

Could you please share/update the link to get access to the discord server? Thanks a lot! 

Best, 
Adel

**Comment by mdubus** [comment]
Hello @Adel-Moumen ! 

We fixed the invitation link, it should be ok now. Thanks for reporting it 🙏

**Pull request merged**
