### PR TITLE
Add a call to action banner for the cloud

### PR DESCRIPTION
**Pull request by bidoubiwa**
Fixes: #441 

A banner now automatically appears at the top of the page with a call to action to the Meilisearch cloud.

To deactivate the banner, you can add `cloud_banner=false` to the query parameters.

## TODO: 
- [x] Implement banner
- [x] Implement query param
- [x] Implement caching of banner visibility

### CODE REVIEW

**Comment by mdubus** [comment]
As commented [here](https://github.com/meilisearch/mini-dashboard/issues/441#issuecomment-1592432760), couldn't we use the referral to prevent the banner from being displayed if we come from the cloud? It would prevent us from adding the query param on the Cloud on every link to the mini-dashboard 😄

**Comment by bidoubiwa** [comment]
It depends on when we would like to use remove the banner. If it is only when someone clicks on their meilisearch instance through the cloud than yes. But if we want to provide a like to share to the search preview without the banner, than it wouldn't work.

**Comment by mdubus** [comment]
> It depends on when we would like to use remove the banner. If it is only when someone clicks on their meilisearch instance through the cloud than yes. But if we want to provide a like to share to the search preview without the banner, than it wouldn't work.
 
Make sense. Thanks a lot 🙏

**Review by mdubus — APPROVED** [review]
LGTM ✨🦕

**Comment by bidoubiwa** [comment]
⚠️ If this PR is merged, we need to inform the cloud so that they can implement the query parameter.

**Comment by bidoubiwa** [comment]
bors merge

**Pull request merged**
