### PR TITLE
Added api-key warning banner

### LINKED ISSUE #434: Display a warning/message if the api_key url parameter is found
Since https://github.com/meilisearch/mini-dashboard/pull/416 has been merged, it is now possible to pass an API key in the URL to bypass the requirement to manually paste an API key in the interface when first opening the mini dashboard.

This is a really nice user improvement but it has the potential to be a security risk. 

The API key could be used to modify the indexes/documents and so users should be warned not to share the URL containing the API key to any users they don't trust.

One potential solution could be to display a warning to users on the mini dashboard if an `api_key` URL parameter is found.

### PR DESCRIPTION
**Pull request by vaibhav135**
# Pull Request

## Related issue
Fixes #434 

Took creation reference from  #442

## What does this PR do?
- Shows api_key (warning) banner. If the api_key is found in the url.

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

### CODE REVIEW

**Comment by bidoubiwa** [comment]
Hey @vaibhav135,
Thanks a lot for this PR! I'll wait for my PR to be merged as there are going to be a lot of merge conflicts to handle.

**Comment by vaibhav135** [comment]
@bidoubiwa done. Please check.

**Comment by bidoubiwa** [comment]
Hey @vaibhav135 thanks a lot 🙏 The code looks good to me. I'm just checking with @gmourier if we should add the cache on the banner appearance.

**Comment by vaibhav135** [comment]
@bidoubiwa @gmourier any update on this guys?

**Comment by bidoubiwa** [comment]
I'm merging, if change needed i'll add it :)

**Comment by vaibhav135** [comment]
> I'm merging, if change needed i'll add it :)

@bidoubiwa if you need any changes, you can tag me also I will be very happy to do that 😁

**Pull request merged**
