### PR TITLE
Update publish build workflow

### LINKED ISSUE #74: Add check-release script
Add `check-release.sh` script to test that the tag to be released matches the tag inside package.json.
The script can be found [here](https://github.com/meilisearch/meilisearch-js/blob/main/scripts/check-release.sh)

### LINKED ISSUE #75: Edit workflow to upload build to the release
Currently, the [publish-build.yml](https://github.com/meilisearch/mini-dashboard/blob/main/.github/workflows/publish-build.yml) pushes on the existing release and overrides the content of the release. 
We don't need the `Create release` section, and we can replace it by `upload-release-action`.
An example can be found [here](https://github.com/meilisearch/transplant/blob/8d8fe8fd29d1de99909762fa8aecd01a06eb318b/.github/workflows/create_artifacts.yml#L32-L38)

### LINKED ISSUE #76: Edit publish-build to start on release
Currently, the [publish-build.yml](https://github.com/meilisearch/mini-dashboard/blob/main/.github/workflows/publish-build.yml) only works on tag push.
We have to update it, to work on release with type `released`. [See here](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release)

### PR DESCRIPTION
**Pull request by mdubus**
Closes #74 , closes #75 , closes #76

### CODE REVIEW

**Review by curquiza — COMMENTED** [review]
I recommend put your `check-release.sh` file into a `.github/scripts` repo instead of `scripts` since it's only related to GitHub.
(I need to change this in most of the integration repositories)

**Comment by mdubus** [comment]
> I recommend put your `check-release.sh` file into a `.github/scripts` repo instead of `scripts` since it's only related to GitHub.
> (I need to change this in most of the integration repositories)

Done, thanks for the suggestion ! ❤️

**Review by curquiza — APPROVED** [review]
LGTM, let's see later if it works 😂

**Comment by mdubus** [comment]
bors merge

**Pull request merged**
