### PR TITLE
Update css after logo replacement

### LINKED ISSUE #232: New logo makes text underneath hard to center
It is centered but it doesnt look centered: 

Screenshot 2022-01-26 at 19 17 13
Screenshot 2022-01-26 at 19 19 05

### PR DESCRIPTION
**Pull request by mdubus**
Closes #232

### CODE REVIEW

**Review by bidoubiwa — COMMENTED** [review]
The version disapeared :/ 
Screenshot 2022-02-09 at 16 16 21

**Comment by bidoubiwa** [comment]
The version appeared once I added the apiKey!

**Review by bidoubiwa — APPROVED** [review]
LGTM 🔥

**Comment by mdubus** [comment]
bors merge

**Pull request merged**
